### ISSUE TITLE
Nubank´s emails

### ISSUE THREAD

**Issue by abuse-efc** [rix4uni/email-inventory#50]
Considering the violation of intellectual property rights of the trademark owner, we kindly request the removal of all content available on the following URLs which use the Nubank trademark and its emails without having obtained prior authorization:

https://github.com/rix4uni/email-inventory/blob/38f3190cc7aa0ecc3bc9e5db6273b4c1566b7cbe/Emails/nubank.com.br.txt
https://github.com/rix4uni/email-inventory/blob/38f3190cc7aa0ecc3bc9e5db6273b4c1566b7cbe/Emails/nu.com.mx.txt
https://github.com/rix4uni/email-inventory/blob/38f3190cc7aa0ecc3bc9e5db6273b4c1566b7cbe/Emails/nu.com.co.txt

The authorization letter with the trademark owner as proof that we can act on behalf of them is available in this link:  https://njoyjnztcx.s3.amazonaws.com/ee45be5e202a00aa6832c7fc421130f3ffd8c0f9d31a0b5d9e8fd068874944f2.pdf

**Comment by rix4uni** [comment]
I deleted all latest commit from past 6 months, now no one will able to see these file and these emails, expect you and me because i and you know this blob commit id, if you close this issue know one know this commit id even exist including you and me.

I checked my self all commit and i'm unable to find this file any of these files `nubank.com.br.txt`, `nu.com.mx.txt`, `nu.com.co.txt`, you can verify using these commands:
```
git clone https://github.com/rix4uni/email-inventory.git
git -C email-inventory/ --no-pager log --pretty=format:%H | xargs -I{} git -C email-inventory/ --no-pager show {} | grep "nubank.com.br.txt"
```

Please close this issue if you don't have any other request.
